CC=g++
CFLAGS = -lSDL -lSDL_image
GAME = ninjasiege

CODE = main.cpp torre.cpp inimigo.cpp bala.cpp timer.cpp util.cpp botao.cpp 

ninjasiege: main.cpp torre.cpp inimigo.cpp bala.cpp timer.cpp util.cpp botao.cpp 
	$(CC) -o $(GAME) $(CODE) $(CFLAGS)
